fix(CORN-aaa): aaaaa

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,8 +8,8 @@ on:
         required: true
         type: string
 
-      tag_version_old:
-        description: 'Old Tag version'
+      tag_version_current:
+        description: 'Current Tag version'
         required: false
         type: string
 
@@ -34,13 +34,10 @@ jobs:
             exit 1
           fi
 
-          if [ -z "${{ github.event.inputs.tag_version_old }}" ]; then  # Check if input is empty
-            echo "Input 'tag_version_old"
-            exit 1 # Or handle empty input as needed.
-          else
-            echo "Input 'my_input' is: ${{ github.event.inputs.tag_version_old }}"
-            # Actions to perform if the input is NOT empty
-          fi
-
-          
-          
+          if ! [ -z "${{ github.event.inputs.tag_version_old }}" ]; then  # Check if input is not empty
+            if ! git show-ref --verify "refs/tags/${{ github.event.inputs.tag_version_old }}" > /dev/null 2>&1; then
+              echo "Error: Tag ${{ github.event.inputs.tag_version_old }} does not exist"
+              exit 1
+            fi
+          fi      
+  
